const candidatos = {
  "01": { nome: "Canadá", continente: "América do Norte", titulos: "0" },
  "02": { nome: "Estados Unidos", continente: "América do Norte", titulos: "0" },
  "03": { nome: "México", continente: "América do Norte", titulos: "0" },
  "04": { nome: "África do Sul", continente: "África", titulos: "0" },
  "05": { nome: "Alemanha", continente: "Europa", titulos: "4 (Tetracampeão)" },
  "06": { nome: "Arábia Saudita", continente: "Ásia", titulos: "0" },
  "07": { nome: "Argélia", continente: "África", titulos: "0" },
  "08": { nome: "Argentina", continente: "América do Sul", titulos: "3 (Tricampeão)" },
  "09": { nome: "Austrália", continente: "Ásia/Oceania", titulos: "0" },
  "10": { nome: "Áustria", continente: "Europa", titulos: "0" },
  "11": { nome: "Bélgica", continente: "Europa", titulos: "0" },
  "12": { nome: "Bósnia e Herzegovina", continente: "Europa", titulos: "0" },
  "13": { nome: "Brasil", continente: "América do Sul", titulos: "5 (Pentacampeão)" },
  "14": { nome: "Cabo Verde", continente: "África", titulos: "0" },
  "15": { nome: "Catar", continente: "Ásia", titulos: "0" },
  "16": { nome: "Colômbia", continente: "América do Sul", titulos: "0" },
  "17": { nome: "Costa do Marfim", continente: "África", titulos: "0" },
  "18": { nome: "Coreia do Sul", continente: "Ásia", titulos: "0" },
  "19": { nome: "Croácia", continente: "Europa", titulos: "0" },
  "20": { nome: "Curaçao", continente: "América Central", titulos: "0" },
  "21": { nome: "Egito", continente: "África", titulos: "0" },
  "22": { nome: "Equador", continente: "América do Sul", titulos: "0" },
  "23": { nome: "Escócia", continente: "Europa", titulos: "0" },
  "24": { nome: "Espanha", continente: "Europa", titulos: "1 (Campeão)" },
  "25": { nome: "França", continente: "Europa", titulos: "2 (Bicampeão)" },
  "26": { nome: "Gana", continente: "África", titulos: "0" },
  "27": { nome: "Haiti", continente: "América Central", titulos: "0" },
  "28": { nome: "Holanda", continente: "Europa", titulos: "0" },
  "29": { nome: "Inglaterra", continente: "Europa", titulos: "1 (Campeão)" },
  "30": { nome: "Iraque", continente: "Ásia", titulos: "0" },
  "31": { nome: "Japão", continente: "Ásia", titulos: "0" },
  "32": { nome: "Jordânia", continente: "Ásia", titulos: "0" },
  "33": { nome: "Marrocos", continente: "África", titulos: "0" },
  "34": { nome: "Noruega", continente: "Europa",
